### PR TITLE
Grammar fixes; removed ‘the’, added object to verb

### PR DESCRIPTION
**Pull request by xerosum**

### CODE REVIEW

**Review by richeney — APPROVED** [review]
Thanks! I'm normally accused of being the grammar police around here but you are 100% correct.  

I must have typed it late at night.... ;)

**Comment by xerosum** [comment]
:) 

Really nice guide btw

**Comment by richeney** [comment]
Cheers – I’m working on a Terraform one now!

**Comment by xerosum** [comment]
I'm going through them avidly, very useful. 

What's with the Citadel branding, am I missing something very obvious?

**Comment by benc-uk** [comment]
It's a nerdy Game Of Thrones reference :)
http://gameofthrones.wikia.com/wiki/The_Citadel
And a cool sounding name (IMO) as a bonus

**Comment by xerosum** [comment]
Surprisingly effective -- I listened to that ARM Azure podcast and did think 'Citadel?!' Doesn't sound like your average Azure guide..

**Comment by richeney** [comment]
I’m hereby renaming the admin group for the repo to The Enclave.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
