### PR TITLE
SAP systems journey 

### PR DESCRIPTION
**Pull request by PmeshramPM**
I have written a small IP which lists the steps of SAP systems journey into Azure and how Azure services helps to unlock the value of SAP data.

### CODE REVIEW

**Comment by benc-uk** [comment]
Hi @PankajMeshramCSA 

Please take a look at the image links they seem to be pointing to a path on your machine e.g. `(\Users\pameshra\OneDrive - Microsoft\AZURE_TECHNOLOGIES\citadel_Repo\azurecitadel.github.io-1\specialised\images\sapjourney.jpg`

I think that should be changed to 
`images\sapjourney.jpg`

Also the tags in the front matter should be all lower case, it's a style thing :)

**Comment by benc-uk** [comment]
Images are actually in the wrong location!

They should be in 
`specalised/sapjourney/images`

You will need to create the sapjourney folder, it should be the same name as the .md file for the content, then linking to them with `images\sapjourney.jpg` will work

**Comment by PmeshramPM** [comment]
Thanks for checking Ben, I have fixed the Tags and images patch as suggested and pushed the code to my repo as well. Do I need to create another pull request?

**Comment by benc-uk** [comment]
Looking good now!

**Comment by PmeshramPM** [comment]
Thanks😊

Pankaj Meshram
Cloud Solution Architect- SAP on Azure
United Kingdom
One Commercial Partner
Phone: +44 (118) 9095515
Mobile: +44 7973 667128
pankaj.meshram@microsoft.com<mailto:pankaj.meshram@microsoft.com>
[micro]

Planned Leave – #
22nd Aug – 12th Sep

**Pull request merged**
